services:
  mysql:
    image: mysql:8.0
    container_name: billing_engine_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: billing_engine
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing_engine_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=billing_engine
      - PORT=8080
    ports:
      - "8080:8080"
    restart: on-failure
    # Run setup script before starting the app, dummy data creation
    command: >
      sh -c "go run scripts/setup_db.go && /app/server"

volumes:
  mysql_data:
